#redis
redis:
  dbAddress: 127.0.0.1:16379 #redis地址 目前仅支持单机，默认即可
  dbMaxIdle: 128
  dbMaxActive: 0
  dbIdleTimeout: 120
  dbPassWord: openIM #redis密码 建议修改

#log
log:
  storageLocation: ../logs/
  rotationTime: 24
  remainRotationCount: 3 #日志数量
  #日志级别 6表示全都打印，测试阶段建议设置为6
  remainLogLevel: 4
  elasticSearchSwitch: false
  elasticSearchAddr: [ 127.0.0.1:9201 ]
  elasticSearchUser: ""
  elasticSearchPassword: ""

#token config
tokenpolicy:
  accessSecret: "open_im_server" #token生成相关，默认即可
  # Token effective time day as a unit
  accessExpire: 3650 #token过期时间（天） 默认即可

#etcd
etcd:
  etcdSchema: openIM  #默认即可
  etcdAddr: [ 127.0.0.1:2379 ] #单机部署时，默认即可

#rpcRegisterName
rpcregistername: #rpc注册服务名，默认即可
  openImUserName: User
  openImFriendName: Friend
  openImOfflineMessageName: OfflineMessage
  openImPushName: Push
  openImOnlineMessageRelayName: OnlineMessageRelay
  openImGroupName: Group
  openImAuthName: Auth
  OpenImStatisticsName: Statistics
  OpenImMessageCMSName: MessageCMS
  openImAdminCMSName: AdminCMS
  openImOfficeName: Office